### PR TITLE
add brew installation note to readme

### PR DESCRIPTION
**Pull request by kaizensoze**

### CODE REVIEW

**Comment by epixoip** [comment]
At this time I'm not sure we should officially recommend users obtain hashcat from downstream distributions, the official recommendation is to download from hashcat.net. Tracking all of the people/projects who choose to distribute hashcat builds isn't our job. So I'm not able to provide signoff for this PR.

**Comment by jsteube** [comment]
I never used any OSX before, but from your discussion I guess this is some sort of package mangement like APT is. Hard for me to decide what I don't know. Do we already have some sort of package for OSX and who made it? 

I tend to agree to @epixoip the primary source for downloading binaries package is https://hashcat.net but OTOH if we have dedicated packages, for example for ubuntu, it should be easier for new users to use this way. Need more information.

**Comment by jsteube** [comment]
no response = close, please recreate if needed

**Comment by magnumripper** [comment]
FWIW: Installing via Homebrew can be an automated build from original source (a "recipe"). This is more or less a ruby script simply downloading all deps and building (I'd endorse that for JtR). Or it can be a binary build (a "cask"). In this case it's apparently the latter, which is a pity.

```
$ brew cask info hashcat
hashcat: 2.00
hashcat
https://hashcat.net/hashcat/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/hashcat.rb
==> Contents
  hashcat-2.00/hashcat-cli64.app (binary)
```

Not sure why anyone would want to download a binary build from someone else than http://hashcat.net.

**Pull request closed without merging**
