### PR TITLE
build instruction: typo

### PR DESCRIPTION
**Pull request by philsmd**
fixes a typo/language

### CODE REVIEW

**Comment by epixoip** [comment]
Did you build & test this change? ;)

**Comment by philsmd** [comment]
yeah I even run "./tools/test.sh -m all -t all -a all" to make sure everything still works, took quite some time ;)

**Comment by epixoip** [comment]
Excellent :P This PR has my signoff to be merged.

**Comment by Xanadrel** [comment]
Seems good to be merged.

**Comment by roycewilliams** [comment]
Whoa, whoa, whoa. Will not compile on my system. We need some serious review on this one before we consider merging. Is it even UTF-8 clean?

**Comment by epixoip** [comment]
@jsteube please merge to master

**Pull request merged**
