### PR TITLE
reorder readme sections

### PR DESCRIPTION
**Pull request by kaizensoze**
Might make sense to get right down to installation first, then alternatively building from source, then usage/help.

### CODE REVIEW

**Comment by epixoip** [comment]
This doesn't seem logical to me, but I might be biased since I wrote the readme ;) Will need other directors to weigh in on this change.

**Comment by jsteube** [comment]
I like the change, I think it's more friendly for complete new users. It would be required to do the same for oclHashat if we do this.

**Comment by jsteube** [comment]
no response = close, please recreate if needed

**Comment by kaizensoze** [comment]
My bad, I thought the PR was waiting on a second board member to be approved.

**Pull request closed without merging**
