### PR TITLE
strip .bin extension on linux platform

### PR DESCRIPTION
**Pull request by lifanov**
It's not customary for Unix-likes to have binary extensions.

### CODE REVIEW

**Comment by Xanadrel** [comment]
Ok for merging.

But I liked extensions.

**Comment by philsmd** [comment]
Another problem with this pull request is that it (silently) introduces avx and avx2 binaries even if the decision was to not build (and therefore recommend) those binaries - right now - (for any platform/architecture) because we currently don't use avx/avx2 intrinsics yet for all of the algorithms that would benefit from it.
The problem and the decision that resulted from this was that people "compared/benchmarked apple vs oranges" and came to strange conclusions.

**Comment by philsmd** [comment]
What I wanted to say is that this pull request introduces a lot of things that have nothing to do with .bin extension and I would therefore not recommend merging this (the whole pull request) because the other stuff seems completely unrelated to .bin.

**Comment by jsteube** [comment]
That's true. There's another problem that for the binary packaging I think it's still "ok" have to have the extension, what do you think? I think an ideal solutions would be to remove the extension as it is inside this PR, but then have the make release target to rename them again and append the extension again.

I'm not so used to github merging yet, is it possible to partially merge change? Or ideally, @lifanov maybe you can send in a new PR with the changes we discussed here.

**Comment by lifanov** [comment]
Yeah, definitely. My bad for lumping extra changes: I should have done this through a feature branch.
However, the other four changes don't actually result in new binaries being built. They only clean up unneeded cruft from the new FreeBSD target.

**Comment by lifanov** [comment]
If they do, please explain because I might not be understanding something.

**Pull request closed without merging**
