### PR TITLE
enable posix targets to build on FreeBSD

### PR DESCRIPTION
**Pull request by lifanov**

### CODE REVIEW

**Comment by lifanov** [comment]
This is basically an ifdef/ifndef shuffling. OSX rules work for FreeBSD.

**Comment by Xanadrel** [comment]
Seems good for merging.

**Comment by jsteube** [comment]
Cool thing, thanks!

**Comment by stufus** [comment]
Only just seen this - I've raised #20 as well (sorry didn't realise this was here)

Note that I needed to modify the makefile to add a specific target and include <sys/types.h> too in the hashcat-cli.c file (because it can't resolve u_int) otherwise. 

Its not obvious, but I was motivated by the fact that I run FreeBSD as a pentesting OS and it was either fix it up or not use hashcat! :-)

**Pull request merged**
